<a href="https://colab.research.google.com/github/beercafeguy/PyMLLab/blob/master/practice/numpy_demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
l = [1,2,3,4,5]
ar = np.array(l)
ar

array([1, 2, 3, 4, 5])

In [3]:
type(ar)

numpy.ndarray

In [4]:
ar_2d = np.array([[1,2],[3,4]])
ar_2d

array([[1, 2],
       [3, 4]])

In [5]:
type(ar_2d)

numpy.ndarray

In [6]:
ar_2d.sum()

10

In [9]:
ar_2d[0,1]

2

In [10]:
ar_2d[1,1]

4

In [11]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [12]:
a = [2,3,4]
np.asanyarray(a)

array([2, 3, 4])

In [13]:
b = np.matrix(l)

In [14]:
b

matrix([[1, 2, 3, 4, 5]])

In [15]:
np.asanyarray(b)

matrix([[1, 2, 3, 4, 5]])

In [16]:
a = np.array(l)

In [17]:
c = a

In [18]:
c

array([1, 2, 3, 4, 5])

In [20]:
c[0]=100

In [21]:
a

array([100,   2,   3,   4,   5])

In [23]:
d = a.copy()

In [24]:
a[1]=200

In [25]:
d

array([100,   2,   3,   4,   5])

In [27]:
np.fromfunction(lambda i,j: i==j,(3,3)) # i and j will be matrix indexes of a 3x3 matrix

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [29]:
iterable = (i * i for i in range(5))
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [31]:
np.fromstring("123 456",sep=" ")

array([123., 456.])

In [32]:
np.fromstring("123,456",sep=",")

array([123., 456.])

In [33]:
# numpy - datatypes

In [34]:
l = [2,3,4,5,6]
ar = np.array(l)

In [35]:
ar.ndim

1

In [36]:
ar2 = np.array([[1,2,3],[4,5,6],[1,4,7]])
ar2.ndim

2

In [37]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [1, 4, 7]])

In [38]:
ar2.size

9

In [40]:
ar2.shape

(3, 3)

In [41]:
ar.dtype

dtype('int64')

In [42]:
ar2.dtype

dtype('int64')

In [43]:
ar2 = np.array([[1,2,3],[4,5,6],[1,4,7.0]])
ar2.dtype

dtype('float64')

In [44]:
list(range(5))

[0, 1, 2, 3, 4]

In [48]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [49]:
list(np.arange(1,10,0.5))

[1.0,
 1.5,
 2.0,
 2.5,
 3.0,
 3.5,
 4.0,
 4.5,
 5.0,
 5.5,
 6.0,
 6.5,
 7.0,
 7.5,
 8.0,
 8.5,
 9.0,
 9.5]

In [50]:
np.arange(1,10,0.5)[1:10]

array([1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [52]:
np.linspace(1,5,10) # produce 10 points between 1 to 5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [53]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [54]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [56]:
np.ones((3,4))*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [57]:
np.empty((3,5))

array([[2.89881990e-316, 0.00000000e+000, 9.17707757e+170,
        6.63062931e+265, 3.88834059e+160],
       [4.00193173e-322, 6.93908507e-310, 6.93908507e-310,
        2.91117695e+257, 2.42766850e-154],
       [2.17371178e+068, 6.01334668e-154, 4.47590761e-091,
        9.77824463e+199, 8.69555537e-322]])

In [58]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [59]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [60]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [61]:
np.logspace(2,5,10,base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [64]:
ar = np.random.randn(3,4)*10
ar

array([[17.21301176, -0.06714927, -6.02144932,  9.16734434],
       [ 8.57623214,  2.68358719, -0.02788329,  0.81382195],
       [ 3.6378828 , -8.04601763, -4.92790516,  3.25911205]])

In [65]:
import pandas as pd 
pd.DataFrame(ar)

0         1         2         3
0  17.213012 -0.067149 -6.021449  9.167344
1   8.576232  2.683587 -0.027883  0.813822
2   3.637883 -8.046018 -4.927905  3.259112

In [66]:
ar = np.random.rand(3,4)*10
ar

array([[8.83868754, 7.0842539 , 7.31929054, 5.55048265],
       [1.93750192, 0.74839279, 1.81362427, 2.98758677],
       [4.58622579, 7.53718266, 7.24691155, 9.57813636]])

In [68]:
pd.DataFrame(ar,columns=['a','b','c','d'])

a         b         c         d
0  8.838688  7.084254  7.319291  5.550483
1  1.937502  0.748393  1.813624  2.987587
2  4.586226  7.537183  7.246912  9.578136

In [69]:
np.random.randint(1,110,(3,4))

array([[ 79,  66,  20,  27],
       [ 34,  40,  62,  37],
       [ 50, 102,  65,  25]])

In [70]:
pd.DataFrame(np.random.randint(1,110,(3,4)))

0   1   2   3
0  68  92  77  90
1  71   2  48  42
2  36  29  75  74

In [71]:
pd.DataFrame(np.random.randint(1,110,(3,4))).to_csv('random_data.csv')

In [72]:
!ls -ltr

total 8
drwxr-xr-x 1 root root 4096 Feb 24 14:38 sample_data
-rw-r--r-- 1 root root   50 Feb 28 16:25 random_data.csv


In [74]:
ar = np.random.rand(3,4).reshape(6,2)
ar

array([[0.15749694, 0.42263066],
       [0.8869679 , 0.98822598],
       [0.37595254, 0.86703224],
       [0.95524818, 0.60585516],
       [0.78473815, 0.90719066],
       [0.07498577, 0.32677634]])

In [75]:
np.random.rand(3,4).reshape(6,-1)

array([[0.65969792, 0.22700623],
       [0.54844405, 0.70050177],
       [0.27423375, 0.32137877],
       [0.25371632, 0.89233525],
       [0.81214782, 0.27752366],
       [0.26318006, 0.54614372]])

In [76]:
ar

array([[0.15749694, 0.42263066],
       [0.8869679 , 0.98822598],
       [0.37595254, 0.86703224],
       [0.95524818, 0.60585516],
       [0.78473815, 0.90719066],
       [0.07498577, 0.32677634]])

In [78]:
ar[1][1]

0.988225980187324

In [79]:
ar[1,1]

0.988225980187324

In [81]:
ar[2:5][1]

array([0.95524818, 0.60585516])

In [82]:
ar

array([[0.15749694, 0.42263066],
       [0.8869679 , 0.98822598],
       [0.37595254, 0.86703224],
       [0.95524818, 0.60585516],
       [0.78473815, 0.90719066],
       [0.07498577, 0.32677634]])

In [84]:
arr = np.random.randint(1,100,(5,5))
arr

array([[49, 46, 92, 99, 97],
       [ 7, 38, 86, 11, 30],
       [89, 13, 14, 23, 40],
       [85, 35, 59, 63, 64],
       [48, 68, 96, 75, 10]])

In [86]:
arr[arr > 50]

array([92, 99, 97, 86, 89, 85, 59, 63, 64, 68, 96, 75])

In [90]:
arr[2:4,[1,2]]

array([[13, 14],
       [35, 59]])

In [92]:
arr[0,0]

49

In [93]:
arr[0,0]=500
arr

array([[500,  46,  92,  99,  97],
       [  7,  38,  86,  11,  30],
       [ 89,  13,  14,  23,  40],
       [ 85,  35,  59,  63,  64],
       [ 48,  68,  96,  75,  10]])

In [95]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [96]:
arr1

array([[2, 2, 2],
       [2, 1, 1],
       [2, 2, 1]])

In [97]:
arr2

array([[2, 2, 2],
       [1, 2, 2],
       [1, 1, 2]])

In [98]:
arr1 + arr2

array([[4, 4, 4],
       [3, 3, 3],
       [3, 3, 3]])

In [99]:
arr1 * arr2

array([[4, 4, 4],
       [2, 2, 2],
       [2, 2, 2]])

In [100]:
arr1/arr2

array([[1. , 1. , 1. ],
       [2. , 0.5, 0.5],
       [2. , 2. , 0.5]])

In [102]:
arr1 @ arr2 # matrix mautiplication

array([[ 8, 10, 12],
       [ 6,  7,  8],
       [ 7,  9, 10]])

In [103]:
arr1/0

<ipython-input-103-2e1dc0d9289f>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [104]:
arr1 +100

array([[102, 102, 102],
       [102, 101, 101],
       [102, 102, 101]])

In [105]:
arr1 **2

array([[4, 4, 4],
       [4, 1, 1],
       [4, 4, 1]])

In [106]:
# broadcasting

In [108]:
arr = np.zeros((4,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [109]:
row = np.array([1,2,3,4])
row

array([1, 2, 3, 4])

In [110]:
arr + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [111]:
row.T

array([1, 2, 3, 4])

In [112]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [113]:
cols = np.array([[1,2,3,4]])
cols

array([[1, 2, 3, 4]])

In [116]:
cols.T

array([[1],
       [2],
       [3],
       [4]])

In [115]:
cols.T + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [117]:
arr1 = np.random.randint(1,100,(3,4))
arr1

array([[52, 75, 95, 90],
       [49, 79, 96, 63],
       [14, 33,  3, 20]])

In [118]:
np.sqrt(arr1)

array([[7.21110255, 8.66025404, 9.74679434, 9.48683298],
       [7.        , 8.88819442, 9.79795897, 7.93725393],
       [3.74165739, 5.74456265, 1.73205081, 4.47213595]])

In [119]:
np.exp(arr1)

array([[3.83100800e+22, 3.73324200e+32, 1.81123908e+41, 1.22040329e+39],
       [1.90734657e+21, 2.03828107e+34, 4.92345829e+41, 2.29378316e+27],
       [1.20260428e+06, 2.14643580e+14, 2.00855369e+01, 4.85165195e+08]])

In [120]:
np.log10(arr1)

array([[1.71600334, 1.87506126, 1.97772361, 1.95424251],
       [1.69019608, 1.89762709, 1.98227123, 1.79934055],
       [1.14612804, 1.51851394, 0.47712125, 1.30103   ]])