<a href="https://colab.research.google.com/github/beercafeguy/PyMLLab/blob/master/DL_1_ANN_Bank_Churn_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


import seaborn as sns

In [2]:
import tensorflow as tf

In [9]:
tf.__version__

'2.14.0'

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
!ls -ltr /content/drive/MyDrive/ML_A_Z/Part_8_Deep_Learning/Section_39_Artificial_Neural_Networks_ANN/Python/Churn_Modelling.csv

-rw------- 1 root root 684858 Apr  7  2020 /content/drive/MyDrive/ML_A_Z/Part_8_Deep_Learning/Section_39_Artificial_Neural_Networks_ANN/Python/Churn_Modelling.csv


In [5]:
data_path = '/content/drive/MyDrive/ML_A_Z/Part_8_Deep_Learning/Section_39_Artificial_Neural_Networks_ANN/Python/Churn_Modelling.csv'

In [6]:
df = pd.read_csv(data_path)

In [7]:
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [13]:
X = df.iloc[:,3:-1].values
y = df.iloc[:,-1].values

array([1, 0, 1, ..., 1, 1, 0])

## Encoding Categorical data

In [15]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [16]:
# label encoding for gender column
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [17]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [19]:
# OneHotEncoding for Geography column
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [20]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [21]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=123)

## Feature Scaling

In [22]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [23]:
X_train

array([[ 1.002002  , -0.57946723, -0.57677292, ...,  0.64298333,
         0.97067965, -0.79223731],
       [ 1.002002  , -0.57946723, -0.57677292, ...,  0.64298333,
        -1.030206  ,  0.57024329],
       [-0.998002  , -0.57946723,  1.73378459, ..., -1.55525028,
        -1.030206  , -0.31968114],
       ...,
       [ 1.002002  , -0.57946723, -0.57677292, ...,  0.64298333,
        -1.030206  , -1.06263427],
       [ 1.002002  , -0.57946723, -0.57677292, ...,  0.64298333,
         0.97067965,  1.1409838 ],
       [ 1.002002  , -0.57946723, -0.57677292, ...,  0.64298333,
        -1.030206  , -1.58131877]])