<a href="https://colab.research.google.com/github/beercafeguy/PyMLLab/blob/master/DL_Day_5_HOML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# l1 and l2 regularization


import tensorflow as tf
from tensorflow import keras

In [4]:
layer = keras.layers.Dense(
    100, # number of nodes
    activation = "relu",
    kernel_initializer = "he_normal",kernel_regularizer = keras.regularizers.l2(0.01)
)

In [6]:
from functools import partial


RegularizedDense = partial(
    keras.layers.Dense,
    activation = "elu",
    kernel_initializer = "he_normal",
    kernel_regularizer = keras.regularizers.l2(0.01)
)


model = keras.models.Sequential(
    [
        keras.layers.Flatten(input_shape = [28,28]),
        RegularizedDense(300),
        RegularizedDense(100),
        RegularizedDense(10, activation = "softmax", kernel_initializer = "glorot_uniform")
    ]
)

In [7]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_1 (Flatten)         (None, 784)               0         
                                                                 
 dense_5 (Dense)             (None, 300)               235500    
                                                                 
 dense_6 (Dense)             (None, 100)               30100     
                                                                 
 dense_7 (Dense)             (None, 10)                1010      
                                                                 
Total params: 266610 (1.02 MB)
Trainable params: 266610 (1.02 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


# Dropout

In [8]:
model  = keras.models.Sequential(
    [
        keras.layers.Flatten(input_shape = [28,28]),
        keras.layers.Dropout(rate=0.2),
        keras.layers.Dense(300, activation = "relu", kernel_initializer = "he_normal"),
        keras.layers.Dropout(rate=0.2),
        keras.layers.Dense(100, activation = "relu", kernel_initializer = "he_normal"),
        keras.layers.Dropout(rate=0.2),
        keras.layers.Dense(10, activation="softmax"),
    ]
)

In [9]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_2 (Flatten)         (None, 784)               0         
                                                                 
 dropout (Dropout)           (None, 784)               0         
                                                                 
 dense_8 (Dense)             (None, 300)               235500    
                                                                 
 dropout_1 (Dropout)         (None, 300)               0         
                                                                 
 dense_9 (Dense)             (None, 100)               30100     
                                                                 
 dropout_2 (Dropout)         (None, 100)               0         
                                                                 
 dense_10 (Dense)            (None, 10)               

In [10]:
# rensors and operations

In [12]:
tf.constant([[1,2,3],[4,5,6]]) #matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [13]:
tf.constant(40)

<tf.Tensor: shape=(), dtype=int32, numpy=40>

In [14]:
t1 = tf.constant([[1,2,3],[4,5,6]])

t1.shape

TensorShape([2, 3])

In [15]:
t1.dtype

tf.int32

In [18]:
t1[:,1:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6]], dtype=int32)>

In [19]:
t1 + 10

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16]], dtype=int32)>

In [20]:
t1[..., 1,tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[2],
       [5]], dtype=int32)>

In [22]:
tf.square(t1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)>

In [23]:
t1 @ tf.transpose(t1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

In [25]:
tf.matmul(t1, tf.transpose(t1))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

In [26]:
# no implicit typecasting in tensorflow

t1 = tf.constant([[1,2],[3,4]])
t2 = tf.constant([[1.0,2.1],[3.2,4.3]])


tf.add(t1,t2) # will not work

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2] name: 

In [27]:
tf.add(tf.cast(t1,tf.float32),t2) # will work because of casting

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2. , 4.1],
       [6.2, 8.3]], dtype=float32)>

#Custom Loss Functions


In [28]:
# implementing huber loss

In [29]:
def huber_loss_fun(y_true, y_pred):
  error = y_true - y_pred
  is_small_error = tf.abs(error) < 1
  squared_loss = tf.square(error) / 2
  linear_loss = tf.abs(error) - 0.5

  return tf.where(is_small_error, squared_loss, linear_loss)

In [30]:
model.compile(loss=huber_loss_fun, optimizer="nadam")

In [31]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_2 (Flatten)         (None, 784)               0         
                                                                 
 dropout (Dropout)           (None, 784)               0         
                                                                 
 dense_8 (Dense)             (None, 300)               235500    
                                                                 
 dropout_1 (Dropout)         (None, 300)               0         
                                                                 
 dense_9 (Dense)             (None, 100)               30100     
                                                                 
 dropout_2 (Dropout)         (None, 100)               0         
                                                                 
 dense_10 (Dense)            (None, 10)               