<a href="https://colab.research.google.com/github/beercafeguy/PyMLLab/blob/master/tensorflow_data_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [ ]:
X = tf.range(10)
X

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
dataset = tf.data.Dataset.from_tensor_slices(X)

In [ ]:
dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [ ]:
for item in dataset:
  print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


In [ ]:
for item in dataset.repeat(3):
  print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype

In [ ]:
for item in dataset.repeat(3).batch(7):
  print(item)

tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int32)
tf.Tensor([7 8 9 0 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([4 5 6 7 8 9 0], shape=(7,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)
tf.Tensor([8 9], shape=(2,), dtype=int32)


In [ ]:
dataset = dataset.map(lambda x:x ** 2)
for item in dataset:
  print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(36, shape=(), dtype=int32)
tf.Tensor(49, shape=(), dtype=int32)
tf.Tensor(64, shape=(), dtype=int32)
tf.Tensor(81, shape=(), dtype=int32)


In [ ]:
dataset = dataset.filter(lambda x:x < 20)
for item in dataset:
  print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)


In [2]:
dataset = tf.data.Dataset.range(10).repeat(3)
dataset = dataset.shuffle(buffer_size=5, seed=42).batch(7)
for item in dataset:
  print(item)

tf.Tensor([0 2 3 6 7 9 4], shape=(7,), dtype=int64)
tf.Tensor([5 0 1 1 8 6 5], shape=(7,), dtype=int64)
tf.Tensor([4 8 7 1 2 3 0], shape=(7,), dtype=int64)
tf.Tensor([5 4 2 7 8 9 9], shape=(7,), dtype=int64)
tf.Tensor([3 6], shape=(2,), dtype=int64)


In [9]:
for item in tf.data.Dataset.range(3).repeat(2).shuffle(buffer_size=2, seed=42).repeat(2):
  print(item)

tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)


# Interleaving lines from multiple files

In [10]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [12]:
housing = fetch_california_housing()
X_train_full, X_test, y_train_full, y_test = train_test_split(
    housing.data, housing.target.reshape(-1, 1), random_state=2024) # test_size = 0.25
X_train, X_valid, y_train, y_valid = train_test_split(
    X_train_full, y_train_full, random_state=2024)

In [13]:
scaler = StandardScaler()
scaler.fit(X_train)
X_mean = scaler.mean_
X_std = scaler.scale_

In [14]:
print(X_mean,X_std)

[ 3.86045802e+00  2.87264427e+01  5.40836711e+00  1.09342646e+00
  1.41558501e+03  3.03720818e+00  3.56335917e+01 -1.19572802e+02] [1.88529609e+00 1.25360228e+01 2.13514117e+00 3.89198791e-01
 1.14082058e+03 7.28725220e+00 2.14342921e+00 2.00364568e+00]


In [15]:
import os
import numpy as np
def save_to_multiple_csv_files(data, name_prefix, header=None, n_parts=10):
    housing_dir = os.path.join("datasets", "housing")
    os.makedirs(housing_dir, exist_ok=True)
    path_format = os.path.join(housing_dir, "my_{}_{:02d}.csv")

    filepaths = []
    m = len(data)
    for file_idx, row_indices in enumerate(np.array_split(np.arange(m), n_parts)):
        part_csv = path_format.format(name_prefix, file_idx)
        filepaths.append(part_csv)
        with open(part_csv, "wt", encoding="utf-8") as f:
            if header is not None:
                f.write(header)
                f.write("\n")
            for row_idx in row_indices:
                f.write(",".join([repr(col) for col in data[row_idx]]))
                f.write("\n")
    return filepaths

In [16]:
train_data = np.c_[X_train, y_train]
valid_data = np.c_[X_valid, y_valid]
test_data = np.c_[X_test, y_test]
header_cols = housing.feature_names + ["MedianHouseValue"]
header = ",".join(header_cols)

train_filepaths = save_to_multiple_csv_files(train_data, "train", header, n_parts=20)
valid_filepaths = save_to_multiple_csv_files(valid_data, "valid", header, n_parts=10)
test_filepaths = save_to_multiple_csv_files(test_data, "test", header, n_parts=10)

In [19]:
!ls -ltrh datasets/housing/

total 2.0M
-rw-r--r-- 1 root root 53K Feb 29 02:13 my_train_00.csv
-rw-r--r-- 1 root root 53K Feb 29 02:13 my_train_01.csv
-rw-r--r-- 1 root root 53K Feb 29 02:13 my_train_02.csv
-rw-r--r-- 1 root root 53K Feb 29 02:13 my_train_03.csv
-rw-r--r-- 1 root root 53K Feb 29 02:13 my_train_04.csv
-rw-r--r-- 1 root root 53K Feb 29 02:13 my_train_05.csv
-rw-r--r-- 1 root root 53K Feb 29 02:13 my_train_06.csv
-rw-r--r-- 1 root root 53K Feb 29 02:13 my_train_07.csv
-rw-r--r-- 1 root root 53K Feb 29 02:13 my_train_08.csv
-rw-r--r-- 1 root root 53K Feb 29 02:13 my_train_09.csv
-rw-r--r-- 1 root root 52K Feb 29 02:13 my_train_10.csv
-rw-r--r-- 1 root root 53K Feb 29 02:13 my_train_11.csv
-rw-r--r-- 1 root root 53K Feb 29 02:13 my_train_12.csv
-rw-r--r-- 1 root root 52K Feb 29 02:13 my_train_13.csv
-rw-r--r-- 1 root root 53K Feb 29 02:13 my_train_14.csv
-rw-r--r-- 1 root root 53K Feb 29 02:13 my_train_15.csv
-rw-r--r-- 1 root root 53K Feb 29 02:13 my_train_16.csv
-rw-r--r-- 1 root root 53K Feb 29 02:

In [20]:
import pandas as pd

pd.read_csv(train_filepaths[0]).head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  4.8542      36.0  4.365979   0.953608       713.0  3.675258     33.92   
1  5.3681      26.0  6.048421   1.010526      1915.0  4.031579     34.28   
2  4.4107      22.0  4.125786   1.173585      1842.0  2.316981     37.39   
3  3.2845      45.0  4.551546   1.041237       401.0  2.067010     38.44   
4  2.8750      37.0  3.660134   1.036617      2913.0  1.502321     34.10   

   Longitude  MedianHouseValue  
0    -118.09             1.674  
1    -118.77             1.877  
2    -122.03             2.327  
3    -122.70             1.783  
4    -118.36             3.000

In [21]:
filapath_dataset = tf.data.Dataset.list_files(train_filepaths, seed = 2024)

In [22]:
for item in filapath_dataset:
  print(item)

tf.Tensor(b'datasets/housing/my_train_14.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_02.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_04.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_18.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_07.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_12.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_00.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_06.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_08.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_05.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_13.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_09.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_03.csv', shape=(), dtype=string)
tf.Tensor(b'datasets/housing/my_train_15.csv', shape=(), dtype=string)
tf.Ten

In [26]:
num_readers = 5

dataset = filapath_dataset.interleave(
    lambda filepath:tf.data.TextLineDataset(filepath).skip(1), cycle_length = num_readers, num_parallel_calls = tf.data.experimental.AUTOTUNE
)

In [27]:
for item in dataset.take(10):
  print(item.numpy())

b'3.9864,12.0,5.2558575445173386,0.9831302717900656,2595.0,2.4320524835988753,37.71,-121.73,2.002'
b'3.5294,12.0,14.113821138211382,2.861788617886179,330.0,2.682926829268293,37.8,-119.07,1.607'
b'5.7819,19.0,6.178885630498534,0.9736070381231672,874.0,2.563049853372434,38.5,-122.63,2.656'
b'3.3125,9.0,16.541284403669724,3.1162079510703364,594.0,1.81651376146789,38.7,-123.49,2.954'
b'3.3021,20.0,5.0,1.0271317829457365,2088.0,2.697674418604651,38.29,-122.27,1.527'
b'4.0313,45.0,4.426470588235294,0.9313725490196079,557.0,2.730392156862745,34.19,-118.35,2.091'
b'2.212,19.0,4.47953216374269,0.9961013645224172,1246.0,2.4288499025341133,34.96,-120.42,1.32'
b'2.6635,16.0,4.555555555555555,1.047953216374269,1762.0,2.0608187134502924,38.57,-121.37,1.358'
b'2.0673,24.0,4.409313725490196,1.1519607843137254,1416.0,3.4705882352941178,34.96,-120.43,1.369'
b'2.8889,11.0,3.881818181818182,1.2666666666666666,1584.0,4.8,34.12,-118.25,1.531'


# Data preprocessing

In [29]:
n_inputs = 8

def preprocess(line):
  defs = [0.0] * n_inputs + [tf.constant([], dtype = tf.float32)] # default values
  fields = tf.io.decode_csv(line, record_defaults=defs)

  x = tf.stack(fields[:-1])
  y = tf.stack(fields[-1:])

  return (x - X_mean)/ X_std , y


In [30]:
preprocess(b'2.8889,11.0,3.881818181818182,1.2666666666666666,1584.0,4.8,34.12,-118.25,1.531')

(<tf.Tensor: shape=(8,), dtype=float32, numpy=
 array([-0.5153345 , -1.4140403 , -0.7149639 ,  0.44512007,  0.14762624,
         0.24190079, -0.7061543 ,  0.6601964 ], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.531], dtype=float32)>)

In [33]:
def csv_reader_dataset(filepaths, repeat=1, n_readers=5,
                       n_read_threads=None, shuffle_buffer_size=10000,
                       n_parse_threads=5, batch_size=32):

  filapath_dataset = tf.data.Dataset.list_files(train_filepaths, seed = 2024)
  dataset = filapath_dataset.interleave(
        lambda filepath: tf.data.TextLineDataset(filepath).skip(1),
        cycle_length=n_readers,
        num_parallel_calls=n_read_threads
  )

  preprocessed_dataset = dataset.map(preprocess, num_parallel_calls=n_parse_threads)
  shuffled_dataset = preprocessed_dataset.shuffle(shuffle_buffer_size).repeat(repeat)

  return shuffled_dataset.batch(batch_size).prefetch(1)

In [34]:
train_set = csv_reader_dataset(train_filepaths, batch_size=3)
for X_batch, y_batch in train_set.take(2):
    print("X =", X_batch)
    print("y =", y_batch)
    print()

X = tf.Tensor(
[[-0.54482585 -1.0949599  -0.79592484  0.03606429  0.50701666 -0.00838294
  -0.6548344   0.6052962 ]
 [-1.0966756   0.6599826  -1.080714   -0.05706565  0.21950431  0.26160917
  -0.7714699   0.6601964 ]
 [-0.9271531  -0.21748862 -0.3360649   0.23162572 -0.7219233  -0.02433081
  -0.72948104  1.1243505 ]], shape=(3, 8), dtype=float32)
y = tf.Tensor(
[[1.832]
 [0.972]
 [0.84 ]], shape=(3, 1), dtype=float32)

X = tf.Tensor(
[[-0.03737247  1.8565344  -0.35805556 -0.45214337 -0.47210315 -0.13294609
  -1.3499811   1.224167  ]
 [-1.1194305  -1.0151898   0.22578947  0.56799024 -0.57290775 -0.04729198
   0.7961119  -0.24814768]
 [ 2.1895988  -1.892661    3.3808062   6.739465   -1.1382903  -0.17715037
  -0.883439    1.5635486 ]], shape=(3, 8), dtype=float32)
y = tf.Tensor(
[[1.634]
 [0.875]
 [4.033]], shape=(3, 1), dtype=float32)



In [35]:
train_set = csv_reader_dataset(train_filepaths)
valid_set = csv_reader_dataset(valid_filepaths)
test_set = csv_reader_dataset(test_filepaths)

In [36]:
model = tf.keras.models.Sequential(
    [
        tf.keras.layers.Dense(30, activation="relu", input_shape=X_train.shape[1:]),
        tf.keras.layers.Dense(1)

    ]
)

In [37]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 30)                270       
                                                                 
 dense_1 (Dense)             (None, 1)                 31        
                                                                 
Total params: 301 (1.18 KB)
Trainable params: 301 (1.18 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [39]:
model.compile(loss="mse", optimizer=tf.keras.optimizers.SGD(learning_rate=1e-3))

In [40]:
from tensorflow import keras

In [42]:
batch_size = 32
model.fit(train_set.repeat(), steps_per_epoch=len(X_train) // batch_size, epochs=10, validation_data=valid_set)

Epoch 1/10
362/362 [==============================] - 7s 18ms/step - loss: 0.8390 - val_loss: 0.7689
Epoch 2/10
362/362 [==============================] - 2s 5ms/step - loss: 0.7385 - val_loss: 0.7103
Epoch 3/10
362/362 [==============================] - 2s 5ms/step - loss: 0.6935 - val_loss: 0.6696
Epoch 4/10
362/362 [==============================] - 2s 5ms/step - loss: 0.6519 - val_loss: 0.6369
Epoch 5/10
362/362 [==============================] - 2s 5ms/step - loss: 0.6271 - val_loss: 0.6098
Epoch 6/10
362/362 [==============================] - 3s 9ms/step - loss: 0.6006 - val_loss: 0.5891
Epoch 7/10
362/362 [==============================] - 2s 5ms/step - loss: 0.5838 - val_loss: 0.5712
Epoch 8/10
362/362 [==============================] - 2s 4ms/step - loss: 0.5622 - val_loss: 0.5552
Epoch 9/10
362/362 [==============================] - 2s 6ms/step - loss: 0.5485 - val_loss: 0.5425
Epoch 10/10
362/362 [==============================] - 2s 5ms/step - loss: 0.5391 - val_loss: 0.531

# The TFRecord Format

In [43]:
with tf.io.TFRecordWriter("my_data.tfrecord") as f:
  f.write("Firdt record")
  f.write("second record")

In [44]:
!ls -ltr

total 12
drwxr-xr-x 1 root root 4096 Feb 27 14:34 sample_data
drwxr-xr-x 3 root root 4096 Feb 29 02:13 datasets
-rw-r--r-- 1 root root   57 Feb 29 02:46 my_data.tfrecord


In [46]:
filepaths = ["my_data.tfrecord"]

dataset = tf.data.TFRecordDataset(filepaths)
for item in dataset:
  print(item.numpy())

b'Firdt record'
b'second record'


In [47]:
options = tf.io.TFRecordOptions(compression_type="GZIP")
with tf.io.TFRecordWriter("compressed.tfrecord", options) as f:
  f.write("Firdt record")
  f.write("second record")

In [48]:
filepaths = ["compressed.tfrecord"]

dataset = tf.data.TFRecordDataset(filepaths, compression_type = "GZIP")
for item in dataset:
  print(item.numpy())

b'Firdt record'
b'second record'


In [49]:
from tensorflow.train import BytesList, FloatList, Int64List
from tensorflow.train import Feature, Features, Example

In [51]:
person_example = Example(
    features = Features(
        feature = {
            "name":Feature(bytes_list = BytesList(value = [b"Hem"])),
            "age": Feature(int64_list = Int64List(value = [123])),
            "emails": Feature(bytes_list = BytesList(value = [b"Hem@gmail.com",b"hem@yahoo.com"]))
        }
    )
)

In [52]:
with tf.io.TFRecordWriter("persons.tfrec") as f:
  f.write(person_example.SerializeToString())

In [53]:
!ls -ltr

total 20
drwxr-xr-x 1 root root 4096 Feb 27 14:34 sample_data
drwxr-xr-x 3 root root 4096 Feb 29 02:13 datasets
-rw-r--r-- 1 root root   57 Feb 29 02:46 my_data.tfrecord
-rw-r--r-- 1 root root   62 Feb 29 02:48 compressed.tfrecord
-rw-r--r-- 1 root root   93 Feb 29 02:57 persons.tfrec


In [56]:
dataset = tf.data.TFRecordDataset(["persons.tfrec"])
for item in dataset:
  parsed_person = Example()
  parsed_person.ParseFromString(item)
  print(parsed_person)

<ipython-input-56-a4cc742ef2ab>:4: RuntimeWarning: Unexpected end-group tag: Not all data was converted
  parsed_person.ParseFromString(item)
