<a href="https://colab.research.google.com/github/beercafeguy/PyMLLab/blob/master/ML_A_Z/classification/classification_model_selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [6]:
!ls -ltr /content/drive/MyDrive/ML_A_Z/Model_Selection/Classification/Data.csv

-rw------- 1 root root 19635 May  8  2020 /content/drive/MyDrive/ML_A_Z/Model_Selection/Classification/Data.csv


In [7]:
path = '/content/drive/MyDrive/ML_A_Z/Model_Selection/Classification/Data.csv'
df = pd.read_csv(path)
df

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0               1000025                5                        1   
1               1002945                5                        4   
2               1015425                3                        1   
3               1016277                6                        8   
4               1017023                4                        1   
..                  ...              ...                      ...   
678              776715                3                        1   
679              841769                2                        1   
680              888820                5                       10   
681              897471                4                        8   
682              897471                4                        8   

     Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                           1                  1                            2   
1                           4                  5                            7   
2                           1                  1                            2   
3                           8                  1                            3   
4                           1                  3                            2   
..                        ...                ...                          ...   
678                         1                  1                            3   
679                         1                  1                            2   
680                        10                  3                            7   
681                         6                  4                            3   
682                         8                  5                            4   

     Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0              1                3                1        1      2  
1             10                3                2        1      2  
2              2                3                1        1      2  
3              4                3                7        1      2  
4              1                3                1        1      2  
..           ...              ...              ...      ...    ...  
678            2                1                1        1      2  
679            1                1                1        1      2  
680            3                8               10        2      4  
681            4               10                6        1      4  
682            5               10                4        1      4  

[683 rows x 11 columns]

In [8]:
df.isnull().sum()

Sample code number             0
Clump Thickness                0
Uniformity of Cell Size        0
Uniformity of Cell Shape       0
Marginal Adhesion              0
Single Epithelial Cell Size    0
Bare Nuclei                    0
Bland Chromatin                0
Normal Nucleoli                0
Mitoses                        0
Class                          0
dtype: int64

In [9]:
df.shape

(683, 11)

In [11]:
X = df.iloc[:,1:-1].values
y = df.iloc[:,-1].values

In [12]:
X[0:6,:]

array([[ 5,  1,  1,  1,  2,  1,  3,  1,  1],
       [ 5,  4,  4,  5,  7, 10,  3,  2,  1],
       [ 3,  1,  1,  1,  2,  2,  3,  1,  1],
       [ 6,  8,  8,  1,  3,  4,  3,  7,  1],
       [ 4,  1,  1,  3,  2,  1,  3,  1,  1],
       [ 8, 10, 10,  8,  7, 10,  9,  7,  1]])

In [15]:
y[1:6]

array([2, 2, 2, 2, 4])

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=2310)

In [17]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.transform(X_test)

## LogisticRegression

In [18]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train_scaled, y_train)

LogisticRegression(random_state=0)

In [19]:
y_pred = classifier.predict(X_test_scaled)

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score,roc_auc_score
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(roc_auc_score(y_test, y_pred))

[[103   3]
 [  3  62]]
0.9649122807017544
0.9627721335268506


## KNeighborsClassifier

In [21]:
from sklearn.neighbors import KNeighborsClassifier
knn_classifier = KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
knn_classifier.fit(X_train_scaled,y_train)

KNeighborsClassifier()

In [22]:
y_pred = knn_classifier.predict(X_test_scaled)

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score,roc_auc_score
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(roc_auc_score(y_test, y_pred))

[[102   4]
 [  1  64]]
0.9707602339181286
0.9734397677793905


## SVC

In [24]:
from sklearn.svm import SVC
sv_classifier = SVC(kernel='linear')
sv_classifier.fit(X_train_scaled,y_train)

SVC(kernel='linear')

In [26]:
y_pred = sv_classifier.predict(X_test_scaled)

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score,roc_auc_score
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(roc_auc_score(y_test, y_pred))

[[101   5]
 [  2  63]]
0.9590643274853801
0.9610304789550073


## SVC Kernel

In [28]:
from sklearn.svm import SVC
sv_classifier = SVC(kernel='rbf')
sv_classifier.fit(X_train_scaled,y_train)

SVC()

In [29]:
y_pred = sv_classifier.predict(X_test_scaled)

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score,roc_auc_score
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(roc_auc_score(y_test, y_pred))

[[101   5]
 [  2  63]]
0.9590643274853801
0.9610304789550073


## GaussianNB

In [31]:
from sklearn.naive_bayes import GaussianNB
nbc = GaussianNB()
nbc.fit(X_train_scaled,y_train)

GaussianNB()

In [33]:
y_pred = nbc.predict(X_test_scaled)

In [34]:
from sklearn.metrics import confusion_matrix, accuracy_score,roc_auc_score
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(roc_auc_score(y_test, y_pred))

[[99  7]
 [ 1 64]]
0.9532163742690059
0.9592888243831641


## RandomForestClassifier

In [35]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(n_estimators=5,criterion='entropy')
rfc.fit(X_train_scaled,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=5)

In [36]:
y_pred = rfc.predict(X_test_scaled)

In [37]:
from sklearn.metrics import confusion_matrix, accuracy_score,roc_auc_score
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(roc_auc_score(y_test, y_pred))

[[101   5]
 [  1  64]]
0.9649122807017544
0.968722786647315


## DecisionTreeClassifier

In [38]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(max_depth=5,criterion='entropy')
dtc.fit(X_train_scaled,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=5)

In [40]:
y_pred = dtc.predict(X_test_scaled)

In [41]:
from sklearn.metrics import confusion_matrix, accuracy_score,roc_auc_score
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(roc_auc_score(y_test, y_pred))

[[103   3]
 [  3  62]]
0.9649122807017544
0.9627721335268506
