<a href="https://colab.research.google.com/github/beercafeguy/PyMLLab/blob/master/assignments/26_Feb_AssQ.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

In [1]:
import numpy as np
list_ = [ '1','2','3','4','5']
array_list = np.array(object = list_)

In [3]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

**Q1.** Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [4]:
# list_ is a simple python list
type(list_)

list

In [6]:
# array_list is a numpy array which is known as ndarray
type(array_list)

numpy.ndarray

**Q2.** Write a code to print the data type of each and every element of both the variables list_ and
array_list.

In [7]:
# for list_
for i in list_:
  print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [11]:
# for array_list
for data in array_list:
  print(type(data))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


**Q3.** Considering the following changes in the variable, array_list:

In [12]:
array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [13]:
# yes in list_ datatype of elements will remain string but in array_list, this will be updated to int64
# for list_
for i in list_:
  print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [14]:
# for array_list
for data in array_list:
  print(type(data))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Consider the below code to answer further questions:

In [16]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

**Q4.** Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [17]:
num_array.shape

(2, 3)

In [18]:
num_array.size

6

**Q5.** Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function. <br>
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [19]:
np.zeros(9).reshape(3,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**Q6.** Create an identity matrix of shape (5,5) using numpy functions? <br>
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])