<a href="https://colab.research.google.com/github/beercafeguy/PyMLLab/blob/master/ML_A_Z/ann/ANN_Bank_Churn_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import numpy as np
import pandas as pd
import  matplotlib.pyplot as plt
import tensorflow as tf

In [25]:
tf.__version__

'2.12.0'

In [26]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [27]:
!ls -ltr /content/drive/MyDrive/ML_A_Z/Part_8_Deep_Learning/Section_39_Artificial_Neural_Networks_ANN/Python/Churn_Modelling.csv

-rw------- 1 root root 684858 Apr  7  2020 /content/drive/MyDrive/ML_A_Z/Part_8_Deep_Learning/Section_39_Artificial_Neural_Networks_ANN/Python/Churn_Modelling.csv


In [28]:
!head -5 /content/drive/MyDrive/ML_A_Z/Part_8_Deep_Learning/Section_39_Artificial_Neural_Networks_ANN/Python/Churn_Modelling.csv

RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
1,15634602,Hargrave,619,France,Female,42,2,0,1,1,1,101348.88,1
2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
3,15619304,Onio,502,France,Female,42,8,159660.8,3,1,0,113931.57,1
4,15701354,Boni,699,France,Female,39,1,0,2,0,0,93826.63,0


In [29]:
path = '/content/drive/MyDrive/ML_A_Z/Part_8_Deep_Learning/Section_39_Artificial_Neural_Networks_ANN/Python/Churn_Modelling.csv'
df = pd.read_csv(path)
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [30]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [31]:
df.shape

(10000, 14)

In [37]:
X = df.iloc[:,3:-1].values
y = df.iloc[:,-1].values

### Data Preprocessing

In [38]:
X[:,2]

array(['Female', 'Female', 'Female', ..., 'Female', 'Male', 'Female'],
      dtype=object)

In [61]:
df.iloc[:,3:-1].values

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [39]:
# encode categorical variables
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

le = LabelEncoder()
ohe = OneHotEncoder()
X[:,2] = le.fit_transform(X[:,2])
ct = ColumnTransformer(transformers=[('encoder',ohe,[1])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

### Train Test Split

In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [41]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.transform(X_test)

### Build ANN

In [42]:
ann = tf.keras.models.Sequential()

In [44]:
# add hidden layer
ann.add(tf.keras.layers.Dense(units = 6,activation='relu')) # 6 = number of neurons in layer, this is a hidden layer
ann.add(tf.keras.layers.Dense(units = 6,activation='relu')) # relu -> rectified linear unit or rectifier

In [45]:
# add output layer
ann.add(tf.keras.layers.Dense(units = 1,activation='sigmoid'))

### Train ANN

In [46]:
# compiling ANN
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [47]:
# train ANN
ann.fit(X_train_scaled,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 3s 2ms/step - loss: 0.5659 - accuracy: 0.7331
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4642 - accuracy: 0.7987
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4412 - accuracy: 0.8045
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4305 - accuracy: 0.8058
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4236 - accuracy: 0.8074
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4170 - accuracy: 0.8116
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4094 - accuracy: 0.8177
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4007 - accuracy: 0.8241
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3917 - accuracy: 0.8294
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3840 - accura

### Make predictions

In [54]:
df.iloc[:,3:-1].values

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [57]:
pred_input

array([['France', '600', 'Male', '40', '3', '60000', '2', '1', '1',
        '50000']], dtype='<U21')

In [72]:
pred_input = np.array([[600,'France','Male',40,3,60000,2,1,1,50000]],dtype='object')
pred_input[:,2] = le.transform(pred_input[:,2])
pred_input = ct.transform(pred_input)
pred_input_scaled = sc.transform(pred_input)
print(pred_input)
print(pred_input_scaled)
ann.predict([[ 0.98560362 ,-0.5698444 , -0.57369368 ,-0.52111599,  0.91601335,  0.10961719,  -0.68538967, -0.2569057  , 0.8095029  , 0.64259497 , 0.9687384 , -0.87203322]])

[[1.0 0.0 0.0 600 1 40 3 60000 2 1 1 50000]]
[[ 0.98560362 -0.5698444  -0.57369368 -0.52111599  0.91601335  0.10961719
  -0.68538967 -0.2569057   0.8095029   0.64259497  0.9687384  -0.87203322]]
1/1 [==============================] - 1s 522ms/step


array([[0.01784319]], dtype=float32)

In [73]:
print(ann.predict([[ 0.98560362 ,-0.5698444 , -0.57369368 ,-0.52111599,  0.91601335,  0.10961719,  -0.68538967, -0.2569057  , 0.8095029  , 0.64259497 , 0.9687384 , -0.87203322]]) > 0.5)

1/1 [==============================] - 0s 162ms/step
[[False]]


In [78]:
y_pred = ann.predict(X_test_scaled)
y_pred_bool = y_pred > 0.5
np.concatenate((y_pred_bool.reshape(len(y_pred_bool),1),y_test.reshape(len(y_test),1)),1)

63/63 [==============================] - 0s 3ms/step


array([[0, 0],
       [0, 1],
       [0, 0],
       ...,
       [0, 0],
       [0, 0],
       [0, 0]])

In [79]:
from sklearn.metrics import confusion_matrix,accuracy_score,roc_auc_score
print(confusion_matrix(y_test,y_pred_bool))
print(accuracy_score(y_test,y_pred_bool))
print(roc_auc_score(y_test,y_pred_bool))

[[1493  102]
 [ 186  219]]
0.856
0.7383954487402763
