<a href="https://colab.research.google.com/github/beercafeguy/PyMLLab/blob/master/ML_A_Z/ann/ANN_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# https://archive.ics.uci.edu/datasets
!wget https://archive.ics.uci.edu/static/public/294/combined+cycle+power+plant.zip

--2023-08-12 04:53:33--  https://archive.ics.uci.edu/static/public/294/combined+cycle+power+plant.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified
Saving to: ‘combined+cycle+power+plant.zip’

combined+cycle+powe     [  <=>               ]   3.50M  8.99MB/s    in 0.4s    

2023-08-12 04:53:34 (8.99 MB/s) - ‘combined+cycle+power+plant.zip’ saved [3674852]



In [3]:
!unzip combined+cycle+power+plant.zip

Archive:  combined+cycle+power+plant.zip
   creating: CCPP/
  inflating: CCPP/Folds5x2_pp.ods    
  inflating: CCPP/Folds5x2_pp.xlsx   
  inflating: CCPP/Readme.txt         
  inflating: CCPP/Readme.txt~        


In [5]:
!ls -ltr CCPP/

total 3676
-rw-rw-r-- 1 root root 2029440 Mar 26  2014 Folds5x2_pp.xlsx
-rw-rw-r-- 1 root root 1723202 Mar 26  2014 Folds5x2_pp.ods
-rw-rw-r-- 1 root root    1738 Mar 26  2014 Readme.txt~
-rw-rw-r-- 1 root root    1793 Mar 26  2014 Readme.txt


In [6]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [7]:
tf.__version__

'2.12.0'

### Import the dataset

In [9]:
!ls -ltr CCPP/Folds5x2_pp.xlsx

-rw-rw-r-- 1 root root 2029440 Mar 26  2014 CCPP/Folds5x2_pp.xlsx


In [10]:
path = 'CCPP/Folds5x2_pp.xlsx'
df = pd.read_excel(path)
df.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [11]:
df.shape

(9568, 5)

In [12]:
df.isnull().sum()

AT    0
V     0
AP    0
RH    0
PE    0
dtype: int64

In [13]:
df.describe()

AT            V           AP           RH           PE
count  9568.000000  9568.000000  9568.000000  9568.000000  9568.000000
mean     19.651231    54.305804  1013.259078    73.308978   454.365009
std       7.452473    12.707893     5.938784    14.600269    17.066995
min       1.810000    25.360000   992.890000    25.560000   420.260000
25%      13.510000    41.740000  1009.100000    63.327500   439.750000
50%      20.345000    52.080000  1012.940000    74.975000   451.550000
75%      25.720000    66.540000  1017.260000    84.830000   468.430000
max      37.110000    81.560000  1033.300000   100.160000   495.760000

In [14]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [15]:
X[2]

array([   5.11,   39.4 , 1012.16,   92.14])

In [16]:
y

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

### Scaling the data

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2023)

In [ ]:
#from sklearn.preprocessing import StandardScaler


### Building ANN

In [20]:
# initialize the network

ann = tf.keras.models.Sequential(layers=[
    tf.keras.layers.Dense(units=6,activation='relu'), # first hidden layer
    tf.keras.layers.Dense(units=6,activation='relu'), # second hidden layer
    tf.keras.layers.Dense(units=1) # output layer
])

### Training ANN

#### Compiling ANN with an optimizer

In [21]:
ann.compile(optimizer='adam',loss='mean_squared_error')

#### Traing using fit

In [22]:
ann.fit(X_train,y_train,epochs=100,batch_size=32)

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 186182.3438
Epoch 2/100
240/240 [==============================] - 0s 981us/step - loss: 4148.8564
Epoch 3/100
240/240 [==============================] - 0s 991us/step - loss: 464.0865
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 415.9192
Epoch 5/100
240/240 [==============================] - 0s 998us/step - loss: 372.4981
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 325.7993
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 280.7095
Epoch 8/100
240/240 [==============================] - 0s 929us/step - loss: 236.1572
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 186.1165
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 142.7668
Epoch 11/100
240/240 [==============================] - 0s 998us/step - loss: 101.3394
Epoch 12/100
240/240 [==============================] - 0s 9

### Predictions

In [23]:
y_pred = ann.predict(X_test)

60/60 [==============================] - 0s 1ms/step


In [25]:
np.printoptions(precision=2)
np.concatenate((y_test.reshape(len(y_test),1),y_pred.reshape(len(y_pred),1)),1)

array([[456.07      , 461.17221069],
       [483.74      , 479.50323486],
       [443.22      , 446.49990845],
       ...,
       [480.74      , 479.11795044],
       [434.26      , 436.36419678],
       [453.5       , 449.92669678]])

In [28]:
from sklearn.metrics import r2_score,mean_absolute_error
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.9109512919960359
4.062404746251918
