<a href="https://colab.research.google.com/github/beercafeguy/PyMLLab/blob/master/grokking_dl/grokking_dl_chapter_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = np.array([0.1,0.2,0.3])
c = np.array([-1,-0.5,0])
d = np.array([0,0,0])


identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
print(a.dot(identity))

[1. 2. 3.]


In [5]:
print(b.dot(identity))

[0.1 0.2 0.3]


In [6]:
print(c.dot(identity))

[-1.  -0.5  0. ]


In [7]:
print(d.dot(identity))

[0. 0. 0.]


In [8]:
this = np.array([2,4,6])
movie = np.array([10,10,10])
rocks = np.array([1,1,1])

In [9]:
print(this + movie + rocks)

[13 15 17]


In [10]:
print((this.dot(identity) + movie).dot(identity)+rocks)

[13. 15. 17.]


Now if I change the order

In [11]:
print((rocks.dot(identity) + movie).dot(identity)+this)

[13. 15. 17.]


Generate sentence embedding using RNN

In [13]:
import numpy as np

def softmax(x_):
  x = np.atleast_2d(x_)
  temp = np.exp(x)
  return temp / np.sum(temp, axis=1, keepdims=True)


word_vects = {}
word_vects['yankees'] = np.array([[0.,0.,0.]])
word_vects['bears'] = np.array([[0.,0.,0.]])
word_vects['braves'] = np.array([[0.,0.,0.]])
word_vects['red'] = np.array([[0.,0.,0.]])
word_vects['sox'] = np.array([[0.,0.,0.]])
word_vects['lose'] = np.array([[0.,0.,0.]])
word_vects['defeat'] = np.array([[0.,0.,0.]])
word_vects['beat'] = np.array([[0.,0.,0.]])
word_vects['tie'] = np.array([[0.,0.,0.]])


sent2output = np.random.rand(3,len(word_vects)) #
identity = np.eye(3)

# forward propogation
layer_0 = word_vects['red']
layer_1 = layer_0.dot(identity) + word_vects['sox']
layer_2 = layer_1.dot(identity) + word_vects['defeat']

pred = softmax(layer_2.dot(sent2output))
print(pred)

[[0.11111111 0.11111111 0.11111111 0.11111111 0.11111111 0.11111111
  0.11111111 0.11111111 0.11111111]]


In [14]:
y = np.array([1,0,0,0,0,0,0,0,0]) # Targets the one-hot vector for “yankees”

pred_delta = pred - y

layer_2_delta = pred_delta.dot(sent2output.T)
defeat_delta = layer_2_delta * 1

layer_1_delta = layer_2_delta.dot(identity.T)
sox_delta = layer_1_delta * 1

layer_0_delta = layer_1_delta.dot(identity.T)

alpha = 0.01
word_vects['red'] = word_vects['red'] - (layer_0_delta * alpha)
word_vects['sox'] -= sox_delta * alpha
word_vects['defeat'] -= defeat_delta * alpha



identity -= np.outer(layer_0,layer_1_delta) * alpha
identity -= np.outer(layer_1,layer_2_delta) * alpha
sent2output -= np.outer(layer_2,pred_delta) * alpha



In [16]:
!wget http://www.thespermwhale.com/jaseweston/babi/tasks_1-20_v1-1.tar.gz tar tasks_1-20_v1-1.tar.gz

--2024-02-20 02:34:22--  http://www.thespermwhale.com/jaseweston/babi/tasks_1-20_v1-1.tar.gz
Resolving www.thespermwhale.com (www.thespermwhale.com)... 50.31.160.191
Connecting to www.thespermwhale.com (www.thespermwhale.com)|50.31.160.191|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1282454 (1.2M) [application/x-gzip]
Saving to: ‘tasks_1-20_v1-1.tar.gz’

tasks_1-20_v1-1.tar 100%[===================>]   1.22M  6.69MB/s    in 0.2s    

2024-02-20 02:34:22 (6.69 MB/s) - ‘tasks_1-20_v1-1.tar.gz’ saved [1282454/1282454]

--2024-02-20 02:34:22--  http://tar/
Resolving tar (tar)... failed: Name or service not known.
wget: unable to resolve host address ‘tar’
--2024-02-20 02:34:22--  http://tasks_1-20_v1-1.tar.gz/
Resolving tasks_1-20_v1-1.tar.gz (tasks_1-20_v1-1.tar.gz)... failed: Name or service not known.
wget: unable to resolve host address ‘tasks_1-20_v1-1.tar.gz’
FINISHED --2024-02-20 02:34:22--
Total wall clock time: 0.4s
Downloaded: 1 files, 1.2M in 0.2s (6

In [18]:
!tar -xvf tasks_1-20_v1-1.tar.gz

tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
tasksv11/
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
tasksv11/en/
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
tasksv11/._LICENSE
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
tasksv11/LICENSE
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown 

In [20]:
!ls -ltr tasksv11/

total 32
drwxr-xr-x 2 154130051 1876110778  4096 Mar 14  2015 shuffled
-rwxr-xr-x 1 154130051 1876110778  2980 Mar 14  2015 README
-rw-r--r-- 1 154130051 1876110778 19561 Apr 10  2015 LICENSE
drwxr-xr-x 2 154130051 1876110778  4096 Feb 20 02:34 en


In [21]:
import sys,random,math
from collections import Counter
import numpy as np

f = open('tasksv11/en/qa1_single-supporting-fact_train.txt','r')
raw = f.readlines()
f.close()

tokens = list()
for line in raw[0:1000]:
  tokens.append(line.lower().replace("\n","").split(" ")[1:])
print(tokens[0:3])

[['mary', 'moved', 'to', 'the', 'bathroom.'], ['john', 'went', 'to', 'the', 'hallway.'], ['where', 'is', 'mary?', '\tbathroom\t1']]


In [22]:
vocab = set()
for sent in tokens:
    for word in sent:
        vocab.add(word)

vocab = list(vocab)


word2index = {}
for i,word in enumerate(vocab):
  word2index[word]=i

In [23]:
def words2indices(sentence):
  idx = list()
  for word in sentence:
    idx.append(word2index[word])
  return idx


def softmax(x):
  e_x = np.exp(x - np.max(x))
  return e_x / e_x.sum(axis=0)

In [24]:
np.random.seed(1)
embed_size = 10

embed = (np.random.rand(len(vocab),embed_size) - 0.5) * 0.1
recurrent = np.eye(embed_size) # initial identity matrix

start = np.zeros(embed_size)
decoder = (np.random.rand(embed_size, len(vocab)) - 0.5) * 0.1

one_hot = np.eye(len(vocab))


In [25]:
def predict(sent):
  layers = list()
  layer = {}
  layer['hidden'] = start
  layers.append(layer)

  loss = 0
  preds = list()

  for target_i in range(len(sent)):
    layer = {}
    layer['pred'] = softmax(layers[-1]['hidden'].dot(decoder))
    loss += -np.log(layer['pred'][sent[target_i]])
    layer['hidden'] = layers[-1]['hidden'].dot(recurrent) + embed[sent[target_i]]
    layers.append(layer)

  return layers, loss