<a href="https://colab.research.google.com/github/beercafeguy/PyMLLab/blob/master/grokking_dl/grokking_dl_chapter_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np



In [2]:
street_lights = np.array(
    [ [ 1, 0, 1 ],
      [ 0, 1, 1 ],
      [ 0, 0, 1 ],
      [ 1, 1, 1 ],
      [ 0, 1, 1 ],
      [ 1, 0, 1 ] ] )

In [3]:
print(street_lights)

[[1 0 1]
 [0 1 1]
 [0 0 1]
 [1 1 1]
 [0 1 1]
 [1 0 1]]


In [4]:
walk_vs_stop = np.array([
    [0],
    [1],
    [0],
    [1],
    [1],
    [0]

])

In [5]:
# both below values are initialized randomly
weights = np.array([0.5,0.48,-0.7])
alpha = 0.1

In [6]:
input = street_lights[0]
true_label = walk_vs_stop[0]

for iter in range(20):
  prediction = input.dot(weights)
  error = (prediction - true_label) ** 2
  delta = prediction - true_label

  weights = weights - (alpha * (input * delta))
  print(f"Error {error} | Prediction {prediction}")

Error [0.04] | Prediction -0.19999999999999996
Error [0.0256] | Prediction -0.15999999999999992
Error [0.016384] | Prediction -0.1279999999999999
Error [0.01048576] | Prediction -0.10239999999999982
Error [0.00671089] | Prediction -0.08191999999999977
Error [0.00429497] | Prediction -0.06553599999999982
Error [0.00274878] | Prediction -0.05242879999999994
Error [0.00175922] | Prediction -0.04194304000000004
Error [0.0011259] | Prediction -0.03355443200000008
Error [0.00072058] | Prediction -0.02684354560000002
Error [0.00046117] | Prediction -0.021474836479999926
Error [0.00029515] | Prediction -0.01717986918399994
Error [0.00018889] | Prediction -0.013743895347199997
Error [0.00012089] | Prediction -0.010995116277759953
Error [7.73712525e-05] | Prediction -0.008796093022207963
Error [4.95176016e-05] | Prediction -0.007036874417766459
Error [3.1691265e-05] | Prediction -0.0056294995342132115
Error [2.02824096e-05] | Prediction -0.004503599627370569
Error [1.29807421e-05] | Prediction -

In [8]:
input = street_lights[0]
true_label = walk_vs_stop[0]

for iter in range(40):
  error_for_all_lights = 0
  for row_index in range(len(street_lights)):
    input = street_lights[row_index]
    true_label = walk_vs_stop[row_index]

    prediction = input.dot(weights)
    error = (prediction - true_label) ** 2

    error_for_all_lights = error_for_all_lights + error
    delta = prediction - true_label

    weights = weights - (alpha * (input * delta))
    print(f"Prediction {prediction}")
  print(f"Error {error_for_all_lights}")

Prediction -0.0020608794820798776
Prediction 0.9980529300742026
Prediction -0.015350039441541376
Prediction 1.0138733908519735
Prediction 0.9972026698331217
Prediction -0.0024139378026368855
Error [0.00044979]
Prediction -0.001931150242109509
Prediction 0.998196644670972
Prediction -0.014307797228519315
Prediction 1.012931308027364
Prediction 0.9974018338541568
Prediction -0.0022602499288213746
Error [0.00039077]
Prediction -0.0018081999430570993
Prediction 0.9983283120705134
Prediction -0.01333631791368297
Prediction 1.0120532081999651
Prediction 0.9975856398077861
Prediction -0.002114964990900369
Error [0.0003395]
Prediction -0.0016919719927202953
Prediction 0.9984492055445909
Prediction -0.012430797779186828
Prediction 1.011234743844143
Prediction 0.9977554954447627
Prediction -0.0019779166840215023
Error [0.00029496]
Prediction -0.0015823333472172012
Prediction 0.9985604213589341
Prediction -0.011586759062928246
Prediction 1.0104718632427012
Prediction 0.9979126403449001
Prediction