<a href="https://colab.research.google.com/github/beercafeguy/PyMLLab/blob/master/grokking_dl/grokking_dl_chapter_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
weight = 0.1

def neural_network(input, weight):
  prediction = input * weight
  return prediction

In [2]:
number_of_toes = [8.5,9.5,10,9]

input = number_of_toes[0]

pred = neural_network(input,weight)

print(pred)

0.8500000000000001


In [3]:
# multiple input neural network

In [4]:

# This is a weighted sum (dot product)
def w_sum(x,w):
  assert(len(x) == len(w))
  return sum([a*b for a,b in zip(x,w)]) # W_transpose * X

![picture](https://drive.google.com/file/d/1bH_pll6Y0ZRujdoeNdxug9-bfxSX8I-e/view?usp=drive_link)

In [5]:
weights = [0.1,0.2,0]

def neural_network(input,weights):
  pred = w_sum(input,weights)
  return pred

In [6]:
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

In [7]:

input_1 = [toes[0],wlrec[0],nfans[0]]

pred = neural_network(input_1,weights)
print(pred)

0.9800000000000001


In [8]:
from statistics import mean

def elementwise_multiplication(vec_a,vec_b):
  return [a*b for a,b in zip(vec_a,vec_b)]


def elementwise_addition(vec_a,vec_b):
  return [a+b for a,b in zip(vec_a,vec_b)]
def vector_sum(vec_a):
  return sum(vec_a)

def vector_average(vec_a):
  return mean(vec_a)

In [9]:
vector_average([1,2,3])

2

In [10]:
def w_sum(x,w):
  assert(len(x) == len(w))
  return vector_sum(elementwise_multiplication(x,w))

In [11]:
pred = neural_network(input_1,weights)
print(pred)

0.9800000000000001


### **implement the same logic in numpy**

In [12]:
import numpy as np

In [13]:
weights = np.array([0.1,0.2,0])

def neural_network(input,weights):
  pred = input.dot(weights)
  return pred

In [14]:
toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0],wlrec[0],nfans[0]])

pred = neural_network(input, weights)
print(pred)

0.9800000000000001


In [16]:
weights = [0.3, 0.2, 0.9]


def scaler_mul(scaler_num,vec):
  return [scaler_num * a for a in vec]

def neural_network(input_num,weights):
  return scaler_mul(input_num,weights)

In [17]:
wlrec = [0.65, 0.8, 0.8, 0.9] # win loss record

input_1 = wlrec[0]

neural_network(input_1,weights)

[0.195, 0.13, 0.5850000000000001]

#### Multiple input multiple output network

In [34]:
def w_sum(a,b):
  assert(len(a) == len(b))
  output = 0
  for i in range(len(a)):
      output += (a[i] * b[i])
  return output


def vec_mul(input_vec,weights_mat):
  output = [0, 0, 0]
  for i in range(len(input_vec)):
    output[i] = w_sum(input_vec,weights_mat[i])

  return output


In [35]:
weights = [[0.1, 0.1, -0.3],
            [0.1, 0.2, 0.0],
            [0.0, 1.3, 0.1]]

def neural_network(input,weights):
  return vec_mul(input,weights)

In [36]:
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65,0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0],wlrec[0],nfans[0]]

pred = neural_network(input,weights)
print(pred)

[0.555, 0.9800000000000001, 0.9650000000000001]


### Multi layer predictions

In [39]:
ih_wgt = [ [0.1, 0.2, -0.1],
           [-0.1,0.1, 0.9],
           [0.1, 0.4, 0.1] ]


hp_wgt = [[0.3, 1.1, -0.3],
          [0.1, 0.2, 0.0],
          [0.0, 1.3, 0.1]]

weights= [ ih_wgt, hp_wgt]


def neural_network(input, weights):
  hid = vec_mul(input,weights[0])
  pred = vec_mul(hid,weights[1])
  return pred


In [40]:
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65,0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0],wlrec[0],nfans[0]]

print(neural_network(input,weights))

[0.21350000000000002, 0.14500000000000002, 0.5065]


# Numpy version

In [41]:
ih_wgt = np.array([[0.1, 0.2, -0.1],
           [-0.1,0.1, 0.9],
           [0.1, 0.4, 0.1]])


hp_wgt = np.array([[0.3, 1.1, -0.3],
          [0.1, 0.2, 0.0],
          [0.0, 1.3, 0.1]])


weights= [ ih_wgt, hp_wgt]


def neural_network(input, weights):
  hid = input.dot(weights[0])
  pred = hid.dot(weights[1])
  return pred

In [44]:
toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65,0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])


input = np.array([toes[0],wlrec[0],nfans[0]])
pred = neural_network(input,weights)
print(pred)

[ 0.496  1.256 -0.286]


In [45]:
a = np.zeros((1,4))
b = np.zeros((4,3))

print(a)
print(b)

[[0. 0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [47]:
print(a.dot(b))

[[0. 0. 0.]]


In [48]:
a = np.array([0,1,2,3])
b = np.array([4,5,6,7])
c = np.array([[0,1,2,3],
              [4,,56,7]])
d = np.zeros((2,4))
e = np.random.rand(2,5)

In [49]:
print(a * b)

[ 0  5 12 21]


In [50]:
print(a * c)

[[ 0  1  4  9]
 [ 0  5 12 21]]


In [51]:
a = np.zeros((2,4))
b = np.zeros((4,3))

c = a.dot(b)
print(c.shape)

(2, 3)


In [52]:
h = np.zeros((5,4))
h.T

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])