<a href="https://colab.research.google.com/github/beercafeguy/PyMLLab/blob/master/grokking_dl/grokking_dl_chapter_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np



In [2]:
street_lights = np.array(
    [ [ 1, 0, 1 ],
      [ 0, 1, 1 ],
      [ 0, 0, 1 ],
      [ 1, 1, 1 ],
      [ 0, 1, 1 ],
      [ 1, 0, 1 ] ] )

In [3]:
print(street_lights)

[[1 0 1]
 [0 1 1]
 [0 0 1]
 [1 1 1]
 [0 1 1]
 [1 0 1]]


In [4]:
walk_vs_stop = np.array([
    [0],
    [1],
    [0],
    [1],
    [1],
    [0]

])

In [5]:
# both below values are initialized randomly
weights = np.array([0.5,0.48,-0.7])
alpha = 0.1

In [6]:
input = street_lights[0]
true_label = walk_vs_stop[0]

for iter in range(20):
  prediction = input.dot(weights)
  error = (prediction - true_label) ** 2
  delta = prediction - true_label

  weights = weights - (alpha * (input * delta))
  print(f"Error {error} | Prediction {prediction}")

Error [0.04] | Prediction -0.19999999999999996
Error [0.0256] | Prediction -0.15999999999999992
Error [0.016384] | Prediction -0.1279999999999999
Error [0.01048576] | Prediction -0.10239999999999982
Error [0.00671089] | Prediction -0.08191999999999977
Error [0.00429497] | Prediction -0.06553599999999982
Error [0.00274878] | Prediction -0.05242879999999994
Error [0.00175922] | Prediction -0.04194304000000004
Error [0.0011259] | Prediction -0.03355443200000008
Error [0.00072058] | Prediction -0.02684354560000002
Error [0.00046117] | Prediction -0.021474836479999926
Error [0.00029515] | Prediction -0.01717986918399994
Error [0.00018889] | Prediction -0.013743895347199997
Error [0.00012089] | Prediction -0.010995116277759953
Error [7.73712525e-05] | Prediction -0.008796093022207963
Error [4.95176016e-05] | Prediction -0.007036874417766459
Error [3.1691265e-05] | Prediction -0.0056294995342132115
Error [2.02824096e-05] | Prediction -0.004503599627370569
Error [1.29807421e-05] | Prediction -

In [7]:
input = street_lights[0]
true_label = walk_vs_stop[0]

for iter in range(40):
  error_for_all_lights = 0
  for row_index in range(len(street_lights)):
    input = street_lights[row_index]
    true_label = walk_vs_stop[row_index]

    prediction = input.dot(weights)
    error = (prediction - true_label) ** 2

    error_for_all_lights = error_for_all_lights + error
    delta = prediction - true_label

    weights = weights - (alpha * (input * delta))
    print(f"Prediction {prediction}")
  print(f"Error {error_for_all_lights}")

Prediction -0.0023058430092137705
Prediction -0.1209223372036855
Prediction -0.4888301034833169
Prediction 0.7512228033816979
Prediction 0.20190057990904375
Prediction 0.2886959509940853
Error [2.2776252]
Prediction 0.23095676079526822
Prediction 0.3095551927482997
Prediction -0.31818022191782463
Prediction 1.0514522876696315
Prediction 0.46917171885649595
Prediction 0.3284202821335913
Error [1.02357959]
Prediction 0.26273622570687305
Prediction 0.5162217243011503
Prediction -0.24916242359281637
Prediction 1.1456228535284017
Prediction 0.6087690510945215
Prediction 0.2934815746795325
Error [0.62555276]
Prediction 0.23478525974362602
Prediction 0.6341885574333014
Prediction -0.21593091088147304
Prediction 1.1692841999678323
Prediction 0.6950870970412221
Prediction 0.24263689344202927
Error [0.41606997]
Prediction 0.19410951475362342
Prediction 0.7123950368134124
Prediction -0.19568909399513768
Prediction 1.1692221409669388
Prediction 0.7556405106568559
Prediction 0.19420853826199794
Err

## Full, batch, and stochastic gradient descent

In [12]:
# First deep neural network

import numpy as np

np.random.seed(2024)


def relu(x):
  return ( x > 0 ) * x

def relu2deriv(output): # slope of relu function
  return output > 0


alpha = 0.2

hidden_size = 4


street_lights = np.array([
    [1, 0, 1],
    [ 0, 1, 1 ],
    [ 0, 0, 1 ],
    [ 1, 1, 1 ]
])
print(street_lights)

walk_vs_stop = np.array([[1, 1, 0, 0]]).T

print(walk_vs_stop)

[[1 0 1]
 [0 1 1]
 [0 0 1]
 [1 1 1]]
[[1]
 [1]
 [0]
 [0]]


In [13]:
weights_0_1 = 2 * np.random.random((3,hidden_size)) - 1
weights_1_2 = 2 * np.random.random((hidden_size,1)) - 1

print(weights_0_1)
print(weights_1_2)

[[ 0.17602904  0.3982175  -0.62369608 -0.91238287]
 [-0.5899621  -0.78787425  0.45448029  0.35880105]
 [-0.05230859 -0.10340835 -0.9617861   0.50519667]]
[[0.20489708]
 [0.92355515]
 [0.32873729]
 [0.21325924]]


In [14]:
for iteration in range(60):

  layer_2_error = 0
  for i in range(len(street_lights)):

    layer_0 = street_lights[i:i+1] # one record at a time
    layer_1 = relu(np.dot(layer_0, weights_0_1))
    layer_2 = np.dot(layer_1, weights_1_2)
    error = (walk_vs_stop[i:i+1] - layer_2) ** 2
    layer_2_error = layer_2_error + (np.sum(error))

    layer_2_delta = walk_vs_stop[i:i+1] - layer_2
    layer_1_delta = layer_2_delta.dot(weights_1_2.T) * relu2deriv(layer_1) # back prop

    weights_1_2 += alpha * layer_1.T.dot(layer_2_delta)
    weights_0_1 += alpha * layer_0.T.dot(layer_1_delta)

  if iteration % 10 == 9:
    print(f"Error: {layer_2_error}")


Error: 0.18451790565944723
Error: 0.040619418540762696
Error: 0.005200984110340061
Error: 0.00045350164863370494
Error: 3.3813122436716266e-05
Error: 2.4049429851076147e-06


In [ ]:
layer_0 = street_lights[0]

layer_1 = relu(np.dot(layer_0, weights_0_1))
layer_2 = np.dot(layer_1, weights_1_2)